-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 23:49:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Schema universidad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `universidad` ;

-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidad` ;
USE `universidad` ;

-- -----------------------------------------------------
-- Table `universidad`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`alumnos` (
  `idalumnos` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(25) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `user` VARCHAR(15) NOT NULL,
  `psw` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idalumnos`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
COMMENT = 'Lista de alumnos';


-- -----------------------------------------------------
-- Table `universidad`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`facultad` (
  `idfacultad` INT NOT NULL AUTO_INCREMENT,
  `nombre_facultad` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `extension` VARCHAR(6) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfacultad`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
COMMENT = 'Listado de facultades';


-- -----------------------------------------------------
-- Table `universidad`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(100) NOT NULL,
  `num_semestres` VARCHAR(2) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `idfacultad` INT NOT NULL,
  PRIMARY KEY (`idcarrera`),
  INDEX `idfacultad_idx` (`idfacultad` ASC) VISIBLE,
  CONSTRAINT `idfacultad`
    FOREIGN KEY (`idfacultad`)
    REFERENCES `universidad`.`facultad` (`idfacultad`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
COMMENT = 'Listado de carreras ofrecidas por la universidad';


-- -----------------------------------------------------
-- Table `universidad`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`matriculas` (
  `idmatriculas` INT NOT NULL AUTO_INCREMENT,
  `desc_matricula` VARCHAR(100) NOT NULL,
  `fecha_inicio_matriculas` DATETIME NOT NULL,
  `fecha_fin_matriculas` DATETIME NOT NULL,
  `idcarrera` INT NOT NULL,
  `vr_matricula` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`idmatriculas`),
  INDEX `idcarrera_FK_idx` (`idcarrera` ASC) VISIBLE,
  CONSTRAINT `idcarrera_FK`
    FOREIGN KEY (`idcarrera`)
    REFERENCES `universidad`.`carrera` (`idcarrera`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
COMMENT = 'Listado de matriculas ';


-- -----------------------------------------------------
-- Table `universidad`.`alumnos_matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`alumnos_matriculas` (
  `idalumnos_matriculas` INT NOT NULL AUTO_INCREMENT,
  `fecha_matricula_alumno` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idalumno` INT NOT NULL,
  `idmatriculas` INT NOT NULL,
  PRIMARY KEY (`idalumnos_matriculas`),
  INDEX `idalumno_idx` (`idalumno` ASC) VISIBLE,
  INDEX `idmatriculas_idx` (`idmatriculas` ASC) VISIBLE,
  CONSTRAINT `idalumno`
    FOREIGN KEY (`idalumno`)
    REFERENCES `universidad`.`alumnos` (`idalumnos`),
  CONSTRAINT `idmatriculas`
    FOREIGN KEY (`idmatriculas`)
    REFERENCES `universidad`.`matriculas` (`idmatriculas`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
COMMENT = 'Lista de alumnos matriculados';


-- -----------------------------------------------------
-- Table `universidad`.`recibo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`recibo_pago` (
  `idrecibo_pago` INT NOT NULL AUTO_INCREMENT,
  `idalumnos_matriculas` INT NOT NULL,
  `fecha_recibo` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `paguese_hasta` DATETIME NOT NULL,
  `pago_total` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`idrecibo_pago`),
  INDEX `idalumnos_matriculas_idx` (`idalumnos_matriculas` ASC) VISIBLE,
  CONSTRAINT `idalumnos_matriculas`
    FOREIGN KEY (`idalumnos_matriculas`)
    REFERENCES `universidad`.`alumnos_matriculas` (`idalumnos_matriculas`))
ENGINE = InnoDB
COMMENT = 'Lista los recibos de pago';


-- -----------------------------------------------------
-- Table `universidad`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`tipo_pago` (
  `idtipo_pago` INT NOT NULL AUTO_INCREMENT,
  `desc_tipo_pago` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo_pago`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
COMMENT = 'Lista los tipos de pago';


-- -----------------------------------------------------
-- Table `universidad`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `fecha_pago` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idrecibo_pago` INT NOT NULL,
  `idtipo_pago` INT NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `idrecibo_pago_idx` (`idrecibo_pago` ASC) INVISIBLE,
  INDEX `idtipo_pago_FK_idx` (`idtipo_pago` ASC) VISIBLE,
  CONSTRAINT `idrecibo_pago_FK`
    FOREIGN KEY (`idrecibo_pago`)
    REFERENCES `universidad`.`recibo_pago` (`idrecibo_pago`),
  CONSTRAINT `idtipo_pago_FK`
    FOREIGN KEY (`idtipo_pago`)
    REFERENCES `universidad`.`tipo_pago` (`idtipo_pago`))
ENGINE = InnoDB
COMMENT = 'Almacena los pagos';


-- -----------------------------------------------------
-- Table `universidad`.`tipo_concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`tipo_concepto` (
  `idtipo_concepto` INT NOT NULL AUTO_INCREMENT,
  `nombre_concepto` VARCHAR(45) NOT NULL,
  `vr_concepto` DECIMAL(8,2) NOT NULL,
  `fecha_inicio_concepto` DATETIME NOT NULL,
  `fecha_fin_concepto` DATETIME NOT NULL,
  PRIMARY KEY (`idtipo_concepto`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
COMMENT = 'Lista los tipo de concepto para pago';


-- -----------------------------------------------------
-- Table `universidad`.`recibo_concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`recibo_concepto` (
  `idtipo_concepto` INT NOT NULL,
  `idrecibo_pago` INT NOT NULL,
  INDEX `idrecibo_pago_idx` (`idrecibo_pago` ASC) VISIBLE,
  INDEX `idtipo_concepto_idx` (`idtipo_concepto` ASC) VISIBLE,
  CONSTRAINT `idrecibo_pago`
    FOREIGN KEY (`idrecibo_pago`)
    REFERENCES `universidad`.`recibo_pago` (`idrecibo_pago`),
  CONSTRAINT `idtipo_concepto`
    FOREIGN KEY (`idtipo_concepto`)
    REFERENCES `universidad`.`tipo_concepto` (`idtipo_concepto`))
ENGINE = InnoDB
COMMENT = 'Almacena los tipos de conceptos de pago junto con el numero de recibo de pago';

